### ISSUE TITLE
Warning bei Parameter skip / Beiträge erscheinen dennoch

### ISSUE THREAD

**Issue by instantflorian** [WBCE/news_img_anywhere#7]
Aufruf mit
`$config = array(	
    'skip' => 'irgendwas'
);
echo getImageNewsItems($config);`

führt zu 

> Warning: explode() expects parameter 2 to be string, array given in /.../modules/news_img_anywhere/include.php on line 198
> 
> Warning: implode() [function.implode]: Invalid arguments passed in /.../modules/news_img_anywhere/include.php on line 203

und die eigentlich zu überspringenden Beiträge erscheinen mit in der Liste.

**Comment by webbird** [comment]
Ich hab's nur mit dem Droplet getestet. Schau ich mir an.

**Comment by webbird** [comment]
Man sollte nicht die gleiche Variable für zwei unterschiedliche Dinge verwenden. Der Fix für Issue #8 sollte auch diesen fixen.

**Comment by instantflorian** [comment]
Its mit https://github.com/WBCE/news_img_anywhere/commit/b95f8737c83e4bf3ca36395bb44a3dc177f3fab5 auch behoben
