### ISSUE TITLE
Angabe von inexistenten Stichworten führt zu unklaren Ergebnissen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/news_img_anywhere#8]
Werden nicht existente Stichworte eingegeben, scheinen immer alle Beiträge in der Liste zu erscheinen, egal, welche Stichworte diese haben. 
Dies geschieht auch, wenn nichtexistente in Kombination mit existenten Stichworten eingegeben werden.
Fall 1:
`$config = array(	
    'tags' => 'TagExistiert,TagExistiertNicht'
);
echo getImageNewsItems($config);`

Erwartetes Ergebnis: es werden nur die Beiträge aufgeführt, denen tatsächlich das Stichwort TagExistiert zugewiesen wurde, und sonst nichts; d.h. im Falle dass es zwar das Stichwort TagExistiert gibt, aber keinen Beitrag dazu, dann eben eine leere Liste.
Tatsächlliches Ergebnis: Es erscheinen alle Beiträge, unabhängig vom Stichwort.

Fall 2:
`$config = array(	
    'tags' => 'TagExistiertNicht'
);
echo getImageNewsItems($config);`

Erwartetes Ergebnis: es keine Beiträge aufgeführt (leere Liste), da es weder das Stichwort gibt, noch Beiträge dazu.
Tatsächlliches Ergebnis: Es erscheinen alle Beiträge, unabhängig vom Stichwort.

Das erscheint mir merkwürdig, oder ist das so beabsichtigt?

**Comment by webbird** [comment]
Interessant dass der Parameter tags funktioniert, skip aber nicht.

**Comment by webbird** [comment]
Teste mal den letzten Commit -> https://github.com/WBCE/news_img_anywhere/commit/b95f8737c83e4bf3ca36395bb44a3dc177f3fab5

**Comment by instantflorian** [comment]
Danke, das sieht gut aus, Problem behoben
